:queues:
  - default

:schedule:
  expire_campaign_worker:
    cron: '* * * * *'   # Runs every 5 minutes
    class: ExpireCampaignWorker
  expire_alert_worker:
    cron: '*/5 * * * *'   # Runs every 5 minutes
    class: ExpireCampaignWorker